export enum TipoEspecialidade {
  PSIQUIATRIA = 'PSIQUIATRIA',

  PSICOLOGIA = 'PSICOLOGIA',

  PSICOPEDAGOGIA = 'PSICOPEDAGOGIA',

  FONOAUDIOLOGIA = 'FONOAUDIOLOGIA',

  TERAPIA_OCUPACIONAL = 'TERAPIA_OCUPACIONAL',

  NEUROPSICOLOGIA = 'NEUROPSICOLOGIA',

  OUTRA = 'OUTRA',
}
