package com.clinica.multiterapias.domain;

import static com.clinica.multiterapias.domain.AssertUtils.bigDecimalCompareTo;
import static com.clinica.multiterapias.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AgendaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaAllPropertiesEquals(Agenda expected, Agenda actual) {
        assertAgendaAutoGeneratedPropertiesEquals(expected, actual);
        assertAgendaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaAllUpdatablePropertiesEquals(Agenda expected, Agenda actual) {
        assertAgendaUpdatableFieldsEquals(expected, actual);
        assertAgendaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaAutoGeneratedPropertiesEquals(Agenda expected, Agenda actual) {
        assertThat(expected)
            .as("Verify Agenda auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaUpdatableFieldsEquals(Agenda expected, Agenda actual) {
        assertThat(expected)
            .as("Verify Agenda relevant properties")
            .satisfies(e ->
                assertThat(e.getDataHoraInicio())
                    .as("check dataHoraInicio")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getDataHoraInicio())
            )
            .satisfies(e ->
                assertThat(e.getDataHoraFim())
                    .as("check dataHoraFim")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getDataHoraFim())
            )
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getObservacoes()).as("check observacoes").isEqualTo(actual.getObservacoes()))
            .satisfies(e ->
                assertThat(e.getValorCobrado())
                    .as("check valorCobrado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getValorCobrado())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaUpdatableRelationshipsEquals(Agenda expected, Agenda actual) {
        assertThat(expected)
            .as("Verify Agenda relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()))
            .satisfies(e -> assertThat(e.getProfissional()).as("check profissional").isEqualTo(actual.getProfissional()))
            .satisfies(e -> assertThat(e.getSala()).as("check sala").isEqualTo(actual.getSala()))
            .satisfies(e -> assertThat(e.getEspecialidade()).as("check especialidade").isEqualTo(actual.getEspecialidade()));
    }
}
