package com.clinica.multiterapias.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EspecialidadeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEspecialidadeAllPropertiesEquals(Especialidade expected, Especialidade actual) {
        assertEspecialidadeAutoGeneratedPropertiesEquals(expected, actual);
        assertEspecialidadeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEspecialidadeAllUpdatablePropertiesEquals(Especialidade expected, Especialidade actual) {
        assertEspecialidadeUpdatableFieldsEquals(expected, actual);
        assertEspecialidadeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEspecialidadeAutoGeneratedPropertiesEquals(Especialidade expected, Especialidade actual) {
        assertThat(expected)
            .as("Verify Especialidade auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEspecialidadeUpdatableFieldsEquals(Especialidade expected, Especialidade actual) {
        assertThat(expected)
            .as("Verify Especialidade relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEspecialidadeUpdatableRelationshipsEquals(Especialidade expected, Especialidade actual) {
        assertThat(expected)
            .as("Verify Especialidade relationships")
            .satisfies(e -> assertThat(e.getProfissionais()).as("check profissionais").isEqualTo(actual.getProfissionais()));
    }
}
