package com.clinica.multiterapias.domain;

import static com.clinica.multiterapias.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfissionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissionalAllPropertiesEquals(Profissional expected, Profissional actual) {
        assertProfissionalAutoGeneratedPropertiesEquals(expected, actual);
        assertProfissionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissionalAllUpdatablePropertiesEquals(Profissional expected, Profissional actual) {
        assertProfissionalUpdatableFieldsEquals(expected, actual);
        assertProfissionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissionalAutoGeneratedPropertiesEquals(Profissional expected, Profissional actual) {
        assertThat(expected)
            .as("Verify Profissional auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissionalUpdatableFieldsEquals(Profissional expected, Profissional actual) {
        assertThat(expected)
            .as("Verify Profissional relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getCpf()).as("check cpf").isEqualTo(actual.getCpf()))
            .satisfies(e -> assertThat(e.getRegistroConselho()).as("check registroConselho").isEqualTo(actual.getRegistroConselho()))
            .satisfies(e -> assertThat(e.getTelefone()).as("check telefone").isEqualTo(actual.getTelefone()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getAtivo()).as("check ativo").isEqualTo(actual.getAtivo()))
            .satisfies(e ->
                assertThat(e.getValorSessao())
                    .as("check valorSessao")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getValorSessao())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissionalUpdatableRelationshipsEquals(Profissional expected, Profissional actual) {
        assertThat(expected)
            .as("Verify Profissional relationships")
            .satisfies(e -> assertThat(e.getEspecialidades()).as("check especialidades").isEqualTo(actual.getEspecialidades()));
    }
}
