package com.clinica.multiterapias.domain;

import static com.clinica.multiterapias.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ProntuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProntuarioAllPropertiesEquals(Prontuario expected, Prontuario actual) {
        assertProntuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertProntuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProntuarioAllUpdatablePropertiesEquals(Prontuario expected, Prontuario actual) {
        assertProntuarioUpdatableFieldsEquals(expected, actual);
        assertProntuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProntuarioAutoGeneratedPropertiesEquals(Prontuario expected, Prontuario actual) {
        assertThat(expected)
            .as("Verify Prontuario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProntuarioUpdatableFieldsEquals(Prontuario expected, Prontuario actual) {
        assertThat(expected)
            .as("Verify Prontuario relevant properties")
            .satisfies(e -> assertThat(e.getTipo()).as("check tipo").isEqualTo(actual.getTipo()))
            .satisfies(e ->
                assertThat(e.getDataAtendimento())
                    .as("check dataAtendimento")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getDataAtendimento())
            )
            .satisfies(e -> assertThat(e.getTitulo()).as("check titulo").isEqualTo(actual.getTitulo()))
            .satisfies(e -> assertThat(e.getConteudo()).as("check conteudo").isEqualTo(actual.getConteudo()))
            .satisfies(e -> assertThat(e.getConfidencial()).as("check confidencial").isEqualTo(actual.getConfidencial()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProntuarioUpdatableRelationshipsEquals(Prontuario expected, Prontuario actual) {
        assertThat(expected)
            .as("Verify Prontuario relationships")
            .satisfies(e -> assertThat(e.getPaciente()).as("check paciente").isEqualTo(actual.getPaciente()))
            .satisfies(e -> assertThat(e.getProfissional()).as("check profissional").isEqualTo(actual.getProfissional()))
            .satisfies(e -> assertThat(e.getAgenda()).as("check agenda").isEqualTo(actual.getAgenda()))
            .satisfies(e -> assertThat(e.getEspecialidade()).as("check especialidade").isEqualTo(actual.getEspecialidade()));
    }
}
