package com.clinica.multiterapias.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAllPropertiesEquals(Sala expected, Sala actual) {
        assertSalaAutoGeneratedPropertiesEquals(expected, actual);
        assertSalaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAllUpdatablePropertiesEquals(Sala expected, Sala actual) {
        assertSalaUpdatableFieldsEquals(expected, actual);
        assertSalaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaAutoGeneratedPropertiesEquals(Sala expected, Sala actual) {
        assertThat(expected)
            .as("Verify Sala auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaUpdatableFieldsEquals(Sala expected, Sala actual) {
        assertThat(expected)
            .as("Verify Sala relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getCapacidade()).as("check capacidade").isEqualTo(actual.getCapacidade()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaUpdatableRelationshipsEquals(Sala expected, Sala actual) {
        // empty method
    }
}
